# Generated by Django 3.1.2 on 2020-10-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsetting',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon/'),
        ),
    ]
